---
title: "index.Rmd"
author: "julie bednarski"
date: "November 29, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#escapement <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1", stringsAsFactors = FALSE)

#write.csv(escapement, "escapement.csv")
escapement <- read.csv("escapement.csv", stringsAsFactors = FALSE)

```

```{r}
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
```
```{r}
median_esc <- escapement %>%
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>%
  group_by(Species, Location, Year) %>%
  summarise(escapement = sum(DailyCount, na.rm = TRUE)) %>%
  group_by(Species) %>%
  summarise(median_escapement = median(escapement))

median_esc
    
```

```{r}
ggplot(median_esc, aes(Species, median_escapement)) + 
  geom_col() +
  coord_flip()
```

```{r}
datatable(median_esc)
```

```{r}
locations <- escapement %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()

leaflet(locations) %>%
  addTiles() %>%
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location)
```
